var GAME_LEVELS = [
  ["                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "       xxxxxxxxxx xxxxxxxxxxxxxxx      xxxx          xxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx   ",
   "     xxxxx     xx xxxxxxxxxxxxxxx    xxx  xxx        xxxx     xxxx    xxxxxxxxxxxxxxxxxxx   ",
   "      xxx              xxxxx         xxx  xxx        xxxx       xxx          xxxxx          ",
   "       xxx             xxxxx        xxx    xxx       xxxx     xxxx           xxxxx          ",
   "         xxxxxx        xxxxx       xxx      xxx      xxxxxxxxxxx             xxxxx          ",
   "            xxxx       xxxxx       xxxxxxxxxxxx      xxxx    xxx             xxxxx          ",
   "    xx        xxx      xxxxx      xxxx      xxxx     xxxx     xxx            xxxxx          ",
   "     xx      xxxxx     xxxxx     xxxxx      xxxxx    xxxx      xxx           xxxxx          ",
   "     xxxx  xxxxxx      xxxxx   xxxxxx        xxxxx   xxxx       xxx          xxxxx          ",
   "      xxxxxxxxx        xxxxx  xxxxxxx        xxxxxx  xxxx        xxx         xxxxx          ",
   "                                                                                            ",
   "                                                                                            ",
   "     @                                                                                      ",
   "                                                                                       o    ",
   "                                                                                            ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
 [" uuuxxxxxxxxxxxxx       xxxxxxxxxxxxxxxx              xxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "uuxxxxxxxxxx           u xxxxxxxxxxxxu                   xxxx xxxxxxxxxxxxxxxx  ",
   "uxxxxxxxxxx               xxxxxxxxxx                       xxxxxxx xxxxxxxxx    ",
   "   xxxxxx                   uxxxxxu                              xxxxxxxxxx     ",
   "      xx                      xxx                                 xx  xxxx      ",
   "      xx                       x                                   x   xx       ",
   "xxxxxxxxxxxxxxxxxxxxx                                     o       xxx   x       ",
   "  xuxxxxxxxxxxxxxxxu                      oo    xxxxxx     o     xx!xx          ",
   "  xu  xxxxxxxxxxx u                      oxxxxxxxuuuu            x!!!x          ",
   "  x    uu xxx                          oo                        xx!xx          ",
   " xx                                  oo                           xvx           ",
   "xxxx                                xxxx ooo                                 xxx",
   "xxxx                   o                    o                                x  ",
   "xxx           u         oo                 o                                ox  ",
   "xxx                  oo  ooo            xxxxxxx                          oo  xxx",
   "xxx          xxxx       oo              xxxxxxx                          oo  x  ",
   "xxx  @       x  x      o                xxxxxxx                  xxxxxxx     x  ",
   "xxxxxxxxxxxxxx  xxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxx ",
   "     xxxxxx      xxx        xx!!!!!xx           xxxxxx     xxxxxx        xxxxx  ",
   "        xx        x          xx!!!x               xxxx!!!!!xxxx            xxx  ",
   "                              x!!!x                  x!!!!!x                x   ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],

  [" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!x  ",
   "                                      x!!x!!xx!!xxxxx     xxxxxxxxxxxxxxxxxxxxxx                             x!x  ",
   "                                      x!!xxxxxxxxxxxxx      xxxxxxxxxxxxxxxxx                                x!x  ",
   "                                      xx!!!!!!!!!!xxxxx!!!!!!xxxxxxxxxxxxxxxx                                x!x  ",
   "                                       xx!!!!!!!!!!!!!!!!!!!!!xxxx                          o  o  o   o   o  x!x  ",
   "                                         x!xxxxxx!xxxxxxxxxxxxxxx                 oo        x  x  x   x   x xx!x  ",
   "                                         xvx      x!x        x    o     o          xxxxxxxxxxxxxxxxxxxxxxxxxx!!x  ",
   "                                                  xvx        x                 xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!xx  ",
   "                                                             xx  xxx  xxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                              xx!!!!!!!!!xx ooo                                   ",
   "                                                               xxxx!!!!!xxxxx                                     ",
   "                                                                  xxxxxxxxxxxxxxx                                 ",
   "                                                                      xx    xxxxxxx ooo             ||   ||    || ",
   " x                                                                    xx    xx                                    ",
   "x!x                                                                   xx    xxxxxxxxxxxxx                         ",
   "x!x                                                                   xx    xx                                    ",
   " v                x                                                   xx    xx            oo                      ",
   "               xxxxxxx                      o o                       xx    xx         xxxxxxxx                   ",
   "              xxxxxxxxx    o o            xxxxxx      o o o           xx    xx                x                   ",
   "             xx   x   xx xxxxxx    o o             xxxxxxxxx    o     xx    xx                x!!!!!!!!!!!!!!!!!!!",
   "     @       x         x         xxxxxx                       xxxx   xxxx  xxxx               x!!!!!!!!!!!!!!!!!!!",
   "    xxx  xx  x         x                                            xxxxxxxxxxxxxxxxxx       xxxxx!!!!!!!!!!!!!xxx",
   "    x x  xx  x         x                                                            xxxx    xxxxxxxxx!!!!!!!xxxxxx",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         =           o    xxxxxxxxxxx!!!!xxxxxxxx",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxx  o o   xxxxxxxxxxxxx!!xxxxxxxxx",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   ["                                                                                              xxxx!!!!!!!!!!!",
   "                                                                                                 xx!!!!!!!!!!!",
   "             ||                                                         o                        xx!!!!!!!!!!!",
   "                                                                        o                         xxxx!!!!!!!!",
   "                                                               o  o   xxxx                        xxxxx!!!!!!!",
   "                                                         oo       xxxxxxxx                        xxxxx!!!!!!!",
   "                                                              xxxxxx     x                          xxxxx!!!!!",
   "                                                     oo    xxxxxx        x                           xxx!!!!!!",
   "                               u                      xxxxxxx            xx             o          =  xx!!!!!!",
   "               ooo  xxxx                xxxxxuuuxxxxxxxxxxxx             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!",
   "                  xxx  xxxxxxxxxxxxxxxxxxxx!!!!!!xxxxxxxx                                              x!!!!!!",
   "            oo  xxx          xxxxxxx         ||                                                        x!!!!!!",
   "         o   xxxx                                                                                      x!!!!!!",
   "     ooo    xxx                                                                                         x vv!!",
   "         xxxx                                                                                               !!",
   "    xxxxxxxx                                                                                                !!",
   "                                                                               o                            !!",
   "xx                oo        o                          ooo                    o o                           !!",
   " xxxxx        oo           xxxx                                          o                                  !!",
   "            o               uu  x             xxxx  xxxxxxxxx           o   xxxxxxxxxx oooooooo  xxx        !!",
   "      xxxxx                      xx     xxx          uuuuu       oo      xxxx       xxxxxxxxxxxxxxxx        !!",
   "          xxxxxxxxxx             xxxxxxxxx                       xxxxxxxxxx                                 !!",
   "                                                                      xxxx  o o  oo  o                      !!",
   "                                                                     xxx   o   o  o  o oo  xxxxxxxxxxxxxxxxxx!",
   "                                                                      xxx     oo o  o   o xx                x!",
   "  xxxxxxxxxxx                                                          xxx   oo o  oo   xxxx u u uu  u  u   x!",
   "  x                                                                                 xxxxxxxx                x!",
   "  x                                            xxxx                           xxxxxxxxu  u u      u     uu  x!",
   "  x  @                                                                      xxxx   u   u u     u u          x!",
   "  xx                             xxxxxxxxxxxxxx!!!x uuu xxxx uuu  xxxxxxxxx  u u u u        u       u       x!",
   "  xxxxxxx=              xxxxxxxxxxxxxxxxxxxxxxx!!!x                     xxx   u    uu  u u u u   u  u u u u x!",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],

  [" !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   " v  v                  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! v   v  ",
   "                                !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                 ",
   "u                                v v      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!      v                    ",
   "                                                 v                    v                                       ",
   "u                                                                                                             ",
   "                                                            ||     ||                                         ",
   "u                                                                                                             ",
   "                                                                                                              ",
   "u                                                  o                                                          ",
   "                                        oo       xxxxxx       o  o   o       o                                ",
   "u                                                                           xxxx                              ",
   "                               oo    xxxxxxx               xxxxxxxxxxxx                oo                     ",
   "u                                                !!!!!!!!!!!!!!!!!!!!!!!!            xxxxxx                   ",
   "                     oo    xxxxxxx        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                     ooo   ",
   "u                  xxxxx      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    xxxxxx   xxxxxx ",
   "                         !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!        xxxxxx ",  
   "u x             xxxx !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    xxxxxx ",
   "  x      @          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx ",
   "u xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "uu!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ",
   "uu!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                                                                                            "],
 
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
